### ISSUE TITLE
Support for MemoryHistory or HashHistory

### ISSUE THREAD

**Issue by jKh98** [salvoravida/redux-first-history#33] opened 2020-09-14 20:52 UTC
Hello, 
I saw your library a couple of days ago and it was just what I was looking for. It works perfectly with redux-toolkit and react-router-dom.
However, I have a question regarding other history types. So far, you are supporting `createBrowserHistory`. I am trying to package my react app using electron-pack as a desktop application, and it's known that electron supports MemoryHistory and HashHistory but not BrowserHistory.
I tried using MemoryHistory and HashHistory with redux-first-history but apparently neither work. Do you think there us a way to do it or will you at least support in future versions?

Thank you

**Comment by salvoravida** [comment] 2020-09-15 13:57
I @jKh98 have you an example of elector use case? a codesanbox?

**Comment by jKh98** [comment] 2020-09-16 07:46
Hello, there is this famous [react-electron-boilerplate project](https://github.com/electron-react-boilerplate/electron-react-boilerplate) where they use connected-react-router (which you are replacing in a very neet way) with createHashHistory.
Do you think something similar is doable here?

Regards

**Comment by salvoravida** [comment] 2020-09-16 16:27
Hi @jKh98  createHash history should be compatible with createbrowserhistory, what is eaxctly the error you have?

**Comment by jKh98** [comment] 2020-10-30 15:40
Hello, It works fine. All I did was removing the router reducer from redux-persist whitelist.

**Comment by jKh98** [comment] 2020-10-30 15:45
However, I am facing a new problem where there is a mismatch between the location state object and the URL in the search bar. This only happens in the case of server redirect. For example, if I am at routeA and received a server redirect to routeB. While in routeB, if I dispatch a replace action to replace routeB with routeA I will successfully be able to go to routeA but the searchbar will show routeB. It is automatically fixed if I reload the page.

**Comment by salvoravida** [comment] 2020-10-31 09:55
> However, I am facing a new problem where there is a mismatch between the location state object and the URL in the search bar. This only happens in the case of server redirect. For example, if I am at routeA and received a server redirect to routeB. While in routeB, if I dispatch a replace action to replace routeB with routeA I will successfully be able to go to routeA but the searchbar will show routeB. It is automatically fixed if I reload the page.

Sorry i cannot understand your use case, without a code sample. are you sure server redirection are inside same domain?

**Comment by salvoravida** [comment] 2020-11-10 05:56
@jKh98 i close this issue, as without code sample i cannot reproduce. feel free to reopen if needed.

**Closed by salvoravida** 2020-11-10 05:56 UTC
