### ISSUE TITLE
[Issue] Redux event not triggered on `navigate` in react-router

### ISSUE THREAD

**Issue by atoztoa** [salvoravida/redux-first-history#14] opened 2019-06-12 14:36 UTC
While using `reach-router` everything works while using a Link.

But, if you use `navigate`, then no event is triggered.

**Comment by salvoravida** [comment] 2019-06-12 15:08
the error is from @reach router that export navigate from globalHistory, ignoring <LocationProvider> history.

**hard Fix on store.js** 

```javascript
import * as Reach from "@reach/router";
import { store, history, reachHistory } from "./store";
Reach.navigate=reachHistory.navigate;  
```

**Comment by atoztoa** [comment] 2019-06-12 16:38
`app.js?1112:42 Uncaught TypeError: Cannot set property navigate of #<Object> which has only a getter`

**Comment by atoztoa** [comment] 2019-06-12 16:46
If I need to use `push` from redux-first-history, do I need to connect it to Redux?

**Comment by salvoravida** [comment] 2019-06-13 10:19
```javascript
import { connect } from "ract-redux";
import { push } from "redux-first-history";
....

class MyComponent ...

this.props.pushUrl('/mypath')

...

export default connect(
state=> ....
dispatch=> ({
pushUrl: (path)=> dispatch(push(path)),
)(MyComponent)
...
})
```

**Comment by salvoravida** [comment] 2019-06-13 10:21
> `app.js?1112:42 Uncaught TypeError: Cannot set property navigate of #<Object> which has only a getter`

the problem is within your bundler.

anyway i suggest to NOT use navigate from reach-router as it not depends on Context Location Provider.

use dispatch push ...

**Comment by salvoravida** [comment] 2019-06-13 14:53
@atoztoa i'm closing this issue. feel free to reopen it if needed.

**Closed by salvoravida** 2019-06-13 14:53 UTC

**Comment by atoztoa** [comment] 2019-06-13 21:37
How can I trigger a `push` from another middleware?

**Comment by atoztoa** [comment] 2019-06-13 21:43
The code in updateLocation needs to be

    return dispatch => {
        dispatch({
              type: CALL_HISTORY_METHOD,
             payload: {
               method: method,
               args: args
            }
         });
        };

**Comment by atoztoa** [comment] 2019-06-13 21:45
Never mind, my bad. Thanks
