### ISSUE TITLE
React-router 6.0.0-beta.0 throws an error

### ISSUE THREAD

**Issue by Ethorsen** [salvoravida/redux-first-history#40] opened 2021-02-05 22:15 UTC
Hi @salvoravida,

Thx for this great module.

There is an error right out of the box with the latest react-router beta.

![Screenshot_1](https://user-images.githubusercontent.com/1493968/107094686-74c9a880-67d5-11eb-890f-e86e89eb0da8.png)

As shown in this sandbox.

https://codesandbox.io/s/proud-hill-e6kn2

Thx

**Comment by salvoravida** [comment] 2021-02-05 22:22
Hi @Ethorsen, the problem is that v beta has a breaking change v alpha.
I have already opened a pr on react router page six months ago. 
https://github.com/ReactTraining/react-router/pull/7586

We cannot. Fix rfh, without that pr merged. Feel free to stress them.. 😅

**Comment by Ethorsen** [comment] 2021-02-05 23:56
Ok.  No stress thx for the follow-up.

I'll stick with react-router 5.2.0 for now as my actual project wont grow that big.  It will be trivial to do the switch once its all figured out.

Thx

**Closed** 2021-08-03 08:44 UTC

**Comment by Ethorsen** [comment] 2021-08-04 19:51
Does it mean your PR with react-router is to be merged soon?

**Comment by salvoravida** [comment] 2021-08-16 12:53
- rewritten in TS
- add support for react-router v6.0.0-beta.1

 ```tsx
import { HistoryRouter as Router } from "redux-first-history/rr6";
import { Route, Routes, Navigate } from "react-router-dom";
//...
import { store, history } from "./store";
//...

      <Router history={history}>
                  <Routes>
                    <Route path="/dashboard" element={<Dashboard />} />
                    <Route path="/" element={<Home />} />
                    <Route path="*" element={<Navigate to="/" />} />
                  </Routes>
      </Router>

 ```



demo rr6 here: https://codesandbox.io/s/redux-first-history-demo-rr6-uccuw
